language: node_js
node_js:
  - "0.10"
  - "0.11"

before_script:
  - mysql -e 'CREATE DATABASE norm_test CHARACTER SET utf8 COLLATE utf8_bin;'

services:
  - memcached # will start memcached
  - mysql
